#ifndef PUTTYPP_FIND_RESOURCE_H
#define PUTTYPP_FIND_RESOURCE_H

#define IDD_FINDDLG 101

#define IDC_FINDDLG_EDIT 1001
#define IDC_FINDDLG_UP 1002
#define IDC_FINDDLG_DOWN 1003
#define IDC_FINDDLG_CLOSE 1004
#define IDC_FINDDLG_GRIP 1005
#define IDC_FINDDLG_IGNORE_CASE 1006
#define IDC_FINDDLG_WHOLE_WORD 1007

#define FINDDLG_INITIAL_WIDTH 186
#define FINDDLG_HEIGHT 26
#endif
