# Makefile for putty under MinGW, Cygwin, or Winelib.
#
# Extra options you can set:
#
#  - COMPAT=-DNO_MULTIMON (Windows only)
#      Disables PuTTY's use of <multimon.h>, which is not available
#      with some development environments. This means that PuTTY's
#      full-screen mode (configurable to work on Alt-Enter) will
#      not behave usefully in a multi-monitor environment.
#
#  - COMPAT=-DNO_HTMLHELP (Windows only)
#      Disables PuTTY's use of <htmlhelp.h>, which is not available
#      with some development environments.
#
#      If you don't have this header, you may be able to use the copy
#      supplied with HTML Help Workshop.
#
#  - RCFL=-DNO_MANIFESTS (Windows only)
#      Disables inclusion of XML application manifests in the PuTTY
#      binaries. This may be necessary to build for 64-bit Windows;
#      the manifests are only included to use the XP GUI style on
#      Windows XP, and the architecture tags are a lie on 64-bit.
#
#  - COMPAT=-DNO_IPV6
#      Disables PuTTY's ability to make IPv6 connections, enabling
#      it to compile under development environments which do not
#      support IPv6 in their header files.
#
#  - COMPAT=-DNO_GSSAPI
#      Disables PuTTY's ability to use GSSAPI functions for
#      authentication and key exchange.
#
#  - COMPAT=-DSTATIC_GSSAPI
#      Causes PuTTY to try to link statically against the GSSAPI
#      library instead of the default of doing it at run time.
#
#  - COMPAT=-DMSVC4 (Windows only)
#  - RCFL=-DMSVC4
#      Makes a couple of minor changes so that PuTTY compiles using
#      MSVC 4. You will also need -DNO_SECURITY and -DNO_MULTIMON.
#
#  - XFLAGS=-DDEBUG
#      Causes PuTTY to enable internal debugging.
#
#  - XFLAGS=-DMINEFIELD (Windows only)
#      Causes PuTTY to use a custom memory allocator, similar in
#      concept to Electric Fence, in place of regular malloc(). Wastes
#      huge amounts of RAM, but should cause heap-corruption bugs to
#      show up as GPFs at the point of failure rather than appearing
#      later on as second-level damage.
#
#  - XFLAGS=-DFUZZING
#      Builds a version of PuTTY with some tweaks to make fuzz testing
#      easier: the SSH random number generator is replaced by one that
#      always returns the same thing.  Note that this makes SSH
#      completely insecure -- a FUZZING build should never be used to
#      connect to a real server.
#
#  - RCFL=-DEMBEDDED_CHM_FILE=\"../$(PUTTY)/doc/putty.chm\"
#
# You can define this path to point at your tools if you need to
# TOOLPATH = c:\cygwin\bin\ # or similar, if you're running Windows
# TOOLPATH = /pkg/mingw32msvc/i386-mingw32msvc/bin/
# TOOLPATH = i686-w64-mingw32-
CC = $(TOOLPATH)gcc
RC = $(TOOLPATH)windres
# Uncomment the following two lines to compile under Winelib
# CC = winegcc
# RC = wrc
# You may also need to tell windres where to find include files:
# RCINC = --include-dir c:\cygwin\include\

OBJDIR := obj
PUTTY := putty-0.85

CFLAGS = -Wall -O2 -std=gnu99 -Wvla -D_WINDOWS -DWIN32S_COMPAT \
		-D_NO_OLDNAMES -D__USE_MINGW_ANSI_STDIO=1 \
		-DHAVE_STRTOUMAX=1 \
		-DHAVE_AES_NI=1 \
		-DHAVE_SHA_NI=1 \
		-DHAVE_SHAINTRIN_H=1 \
		-DHAVE_CLMUL=1 \
		-DHAVE_ADDDLLDIRECTORY=1 \
		-DHAVE_AFUNIX_H=1 \
		-DHAVE_WINRESRC_H=1 \
		-DHAVE_SETDEFAULTDLLDIRECTORIES=1 \
		-DHAVE_GCP_RESULTSW=1 \
		-I../$(PUTTY)/ \
		-I../$(PUTTY)/crypto/ \
		-I../$(PUTTY)/terminal/ \
		-I../$(PUTTY)/windows/ \
		-I$(OBJDIR)/ \
		-I../windows/ \
		-I../windows/sftp
LDFLAGS = -s --static
RCFLAGS = $(RCINC) --define WIN32=1 --define _WIN32=1 --define WINVER=0x0400 \
		-DHAVE_WINRESRC_H=1 \
		-I../$(PUTTY)/ \
		-I../$(PUTTY)/windows/ \
		-I$(OBJDIR)/ \
		-I../windows/

# _WIN32_IE is required to expose identifiers that only make sense on
# systems with IE5+ installed, such as some arguments to SHGetFolderPath().
# WINVER etc perform a similar function for FlashWindowEx().
CFLAGS += -D_WIN32_IE=0x0500
CFLAGS += -DWINVER=0x0500 -D_WIN32_WINDOWS=0x0410 -D_WIN32_WINNT=0x0500

.SUFFIXES:

SOURCES := ../$(PUTTY)/windows/utils/agent_mutex_name.c \
            ../$(PUTTY)/windows/utils/agent_named_pipe_name.c \
            ../$(PUTTY)/windows/utils/arm_arch_queries.c \
            ../$(PUTTY)/windows/utils/aux_match_opt.c \
            ../$(PUTTY)/windows/utils/blink_time.c \
            ../$(PUTTY)/windows/utils/centre_window.c \
            ../$(PUTTY)/windows/utils/cmdline_arg.c \
            ../$(PUTTY)/windows/utils/cryptoapi.c \
            ../$(PUTTY)/windows/utils/defaults.c \
            ../$(PUTTY)/windows/utils/dll_hijacking_protection.c \
            ../$(PUTTY)/windows/utils/dputs.c \
            ../$(PUTTY)/windows/utils/escape_registry_key.c \
            ../$(PUTTY)/windows/utils/filename.c \
            ../$(PUTTY)/windows/utils/fontspec.c \
            ../$(PUTTY)/windows/utils/getdlgitemtext_alloc.c \
            ../$(PUTTY)/windows/utils/get_system_dir.c \
            ../$(PUTTY)/windows/utils/get_username.c \
            ../$(PUTTY)/windows/utils/gui-timing.c \
            ../$(PUTTY)/windows/utils/interprocess_mutex.c \
            ../$(PUTTY)/windows/utils/is_console_handle.c \
            ../$(PUTTY)/windows/utils/load_system32_dll.c \
            ../$(PUTTY)/windows/utils/ltime.c \
            ../$(PUTTY)/windows/utils/makedlgitemborderless.c \
            ../$(PUTTY)/windows/utils/make_spr_sw_abort_winerror.c \
            ../$(PUTTY)/windows/utils/message_box.c \
            ../$(PUTTY)/windows/utils/minefield.c \
            ../$(PUTTY)/windows/utils/open_for_write_would_lose_data.c \
            ../$(PUTTY)/windows/utils/pgp_fingerprints_msgbox.c \
            ../$(PUTTY)/windows/utils/platform_get_x_display.c \
            ../$(PUTTY)/windows/utils/registry.c \
            ../$(PUTTY)/windows/utils/request_file.c \
            ../$(PUTTY)/windows/utils/screenshot.c \
            ../$(PUTTY)/windows/utils/security.c \
            ../$(PUTTY)/windows/utils/split_into_argv.c \
            ../$(PUTTY)/windows/utils/split_into_argv_w.c \
            ../$(PUTTY)/windows/utils/subprocess_waiter.c \
            ../$(PUTTY)/windows/utils/version.c \
            ../$(PUTTY)/windows/utils/win_strerror.c \
            ../$(PUTTY)/utils/antispoof.c \
            ../$(PUTTY)/utils/backend_socket_log.c \
            ../$(PUTTY)/utils/base64_decode_atom.c \
            ../$(PUTTY)/utils/base64_decode.c \
            ../$(PUTTY)/utils/base64_encode_atom.c \
            ../$(PUTTY)/utils/base64_encode.c \
            ../$(PUTTY)/utils/base64_valid.c \
            ../$(PUTTY)/utils/bufchain.c \
            ../$(PUTTY)/utils/buildinfo.c \
            ../$(PUTTY)/utils/burnstr.c \
            ../$(PUTTY)/utils/burnwcs.c \
            ../$(PUTTY)/utils/cert-expr.c \
            ../$(PUTTY)/utils/chomp.c \
            ../$(PUTTY)/utils/cmdline_get_passwd_input_state_new.c \
            ../$(PUTTY)/utils/conf.c \
            ../$(PUTTY)/utils/conf_data.c \
            ../$(PUTTY)/utils/conf_dest.c \
            ../$(PUTTY)/utils/conf_launchable.c \
            ../$(PUTTY)/utils/ctrlparse.c \
            ../$(PUTTY)/utils/ctrlset_normalise.c \
            ../$(PUTTY)/utils/debug.c \
            ../$(PUTTY)/utils/decode_utf8.c \
            ../$(PUTTY)/utils/decode_utf8_to_wchar.c \
            ../$(PUTTY)/utils/decode_utf8_to_wide_string.c \
            ../$(PUTTY)/utils/default_description.c \
            ../$(PUTTY)/utils/dupcat.c \
            ../$(PUTTY)/utils/dupprintf.c \
            ../$(PUTTY)/utils/dupstr.c \
            ../$(PUTTY)/utils/dupwcs.c \
            ../$(PUTTY)/utils/dupwcscat.c \
            ../$(PUTTY)/utils/dup_mb_to_wc.c \
            ../$(PUTTY)/utils/dup_wc_to_mb.c \
            ../$(PUTTY)/utils/encode_utf8.c \
            ../$(PUTTY)/utils/encode_wide_string_as_utf8.c \
            ../$(PUTTY)/utils/fgetline.c \
            ../$(PUTTY)/utils/format_connection_setup_command.c \
            ../$(PUTTY)/utils/host_ca_new_free.c \
            ../$(PUTTY)/utils/host_strchr.c \
            ../$(PUTTY)/utils/host_strchr_internal.c \
            ../$(PUTTY)/utils/host_strcspn.c \
            ../$(PUTTY)/utils/host_strduptrim.c \
            ../$(PUTTY)/utils/host_strrchr.c \
            ../$(PUTTY)/utils/key_components.c \
            ../$(PUTTY)/utils/logeventf.c \
            ../$(PUTTY)/utils/log_proxy_stderr.c \
            ../$(PUTTY)/utils/make_spr_sw_abort_static.c \
            ../$(PUTTY)/utils/marshal.c \
            ../$(PUTTY)/utils/memory.c \
            ../$(PUTTY)/utils/memxor.c \
            ../$(PUTTY)/utils/nullstrcmp.c \
            ../$(PUTTY)/utils/out_of_memory.c \
            ../$(PUTTY)/utils/parse_blocksize.c \
            ../$(PUTTY)/utils/percent_decode.c \
            ../$(PUTTY)/utils/percent_encode.c \
            ../$(PUTTY)/utils/prompts.c \
            ../$(PUTTY)/utils/ptrlen.c \
            ../$(PUTTY)/utils/read_file_into.c \
            ../$(PUTTY)/utils/seat_connection_fatal.c \
            ../$(PUTTY)/utils/seat_dialog_text.c \
            ../$(PUTTY)/utils/seat_nonfatal.c \
            ../$(PUTTY)/utils/sessprep.c \
            ../$(PUTTY)/utils/sk_free_peer_info.c \
            ../$(PUTTY)/utils/smemclr.c \
            ../$(PUTTY)/utils/smemeq.c \
            ../$(PUTTY)/utils/spr_get_error_message.c \
            ../$(PUTTY)/utils/ssh_key_clone.c \
            ../$(PUTTY)/utils/ssh2_pick_fingerprint.c \
            ../$(PUTTY)/utils/sshutils.c \
            ../$(PUTTY)/utils/strbuf.c \
            ../$(PUTTY)/utils/string_length_for_printf.c \
            ../$(PUTTY)/utils/stripctrl.c \
            ../$(PUTTY)/utils/tempseat.c \
            ../$(PUTTY)/utils/tree234.c \
            ../$(PUTTY)/utils/validate_manual_hostkey.c \
            ../$(PUTTY)/utils/version.c \
            ../$(PUTTY)/utils/wcwidth.c \
            ../$(PUTTY)/utils/wildcard.c \
            ../$(PUTTY)/utils/wordwrap.c \
            ../$(PUTTY)/utils/write_c_string_literal.c \
            ../$(PUTTY)/utils/x11authfile.c \
            ../$(PUTTY)/utils/x11authnames.c \
            ../$(PUTTY)/utils/x11_dehexify.c \
            ../$(PUTTY)/utils/x11_identify_auth_proto.c \
            ../$(PUTTY)/utils/x11_make_greeting.c \
            ../$(PUTTY)/utils/x11_parse_ip.c \
            ../$(PUTTY)/crypto/aes-common.c \
            ../$(PUTTY)/crypto/aes-select.c \
            ../$(PUTTY)/crypto/aes-sw.c \
            ../$(PUTTY)/crypto/aesgcm-common.c \
            ../$(PUTTY)/crypto/aesgcm-select.c \
            ../$(PUTTY)/crypto/aesgcm-sw.c \
            ../$(PUTTY)/crypto/aesgcm-ref-poly.c \
            ../$(PUTTY)/crypto/arcfour.c \
            ../$(PUTTY)/crypto/argon2.c \
            ../$(PUTTY)/crypto/bcrypt.c \
            ../$(PUTTY)/crypto/blake2.c \
            ../$(PUTTY)/crypto/blowfish.c \
            ../$(PUTTY)/crypto/chacha20-poly1305.c \
            ../$(PUTTY)/crypto/crc32.c \
            ../$(PUTTY)/crypto/des.c \
            ../$(PUTTY)/crypto/diffie-hellman.c \
            ../$(PUTTY)/crypto/dsa.c \
            ../$(PUTTY)/crypto/ecc-arithmetic.c \
            ../$(PUTTY)/crypto/ecc-ssh.c \
            ../$(PUTTY)/crypto/hash_simple.c \
            ../$(PUTTY)/crypto/hmac.c \
            ../$(PUTTY)/crypto/kex-hybrid.c \
            ../$(PUTTY)/crypto/mac.c \
            ../$(PUTTY)/crypto/mac_simple.c \
            ../$(PUTTY)/crypto/md5.c \
            ../$(PUTTY)/crypto/mlkem.c \
            ../$(PUTTY)/crypto/mpint.c \
            ../$(PUTTY)/crypto/ntru.c \
            ../$(PUTTY)/crypto/openssh-certs.c \
            ../$(PUTTY)/crypto/prng.c \
            ../$(PUTTY)/crypto/pubkey-pem.c \
            ../$(PUTTY)/crypto/pubkey-ppk.c \
            ../$(PUTTY)/crypto/pubkey-ssh1.c \
            ../$(PUTTY)/crypto/rfc6979.c \
            ../$(PUTTY)/crypto/rsa.c \
            ../$(PUTTY)/crypto/sha256-common.c \
            ../$(PUTTY)/crypto/sha256-select.c \
            ../$(PUTTY)/crypto/sha256-sw.c \
            ../$(PUTTY)/crypto/sha512-common.c \
            ../$(PUTTY)/crypto/sha512-select.c \
            ../$(PUTTY)/crypto/sha512-sw.c \
            ../$(PUTTY)/crypto/sha3.c \
            ../$(PUTTY)/crypto/sha1-common.c \
            ../$(PUTTY)/crypto/sha1-select.c \
            ../$(PUTTY)/crypto/sha1-sw.c \
            ../$(PUTTY)/crypto/aesgcm-clmul.c \
            ../$(PUTTY)/crypto/aes-ni.c \
            ../$(PUTTY)/crypto/sha256-ni.c \
            ../$(PUTTY)/crypto/sha1-ni.c \
            ../$(PUTTY)/proxy/cproxy.c \
            ../$(PUTTY)/proxy/sshproxy.c \
            ../$(PUTTY)/crypto/xdmauth.c \
            ../$(PUTTY)/errsock.c \
            ../$(PUTTY)/logging.c \
            ../$(PUTTY)/x11disp.c \
            ../$(PUTTY)/proxy/proxy.c \
            ../$(PUTTY)/proxy/http.c \
            ../$(PUTTY)/proxy/socks4.c \
            ../$(PUTTY)/proxy/socks5.c \
            ../$(PUTTY)/proxy/telnet.c \
            ../$(PUTTY)/proxy/local.c \
            ../$(PUTTY)/proxy/interactor.c \
            ../$(PUTTY)/proxy/newmain.c \
            ../$(PUTTY)/windows/network.c \
            ../$(PUTTY)/windows/handle-socket.c \
            ../$(PUTTY)/windows/named-pipe-client.c \
            ../$(PUTTY)/windows/named-pipe-server.c \
            ../$(PUTTY)/windows/local-proxy.c \
            ../$(PUTTY)/windows/x11.c \
            ../$(PUTTY)/cmdline.c \
            ../$(PUTTY)/settings.c \
            ../$(PUTTY)/windows/storage.c \
            ../$(PUTTY)/otherbackends/raw.c \
            ../$(PUTTY)/otherbackends/rlogin.c \
            ../$(PUTTY)/otherbackends/supdup.c \
            ../$(PUTTY)/otherbackends/telnet.c \
            ../$(PUTTY)/otherbackends/testback.c \
            ../$(PUTTY)/windows/serial.c \
            ../$(PUTTY)/ssh/agentf.c \
            ../$(PUTTY)/ssh/connection1-client.c \
            ../$(PUTTY)/ssh/connection2-client.c \
            ../$(PUTTY)/ssh/kex2-client.c \
            ../$(PUTTY)/ssh/mainchan.c \
            ../$(PUTTY)/ssh/sharing.c \
            ../$(PUTTY)/ssh/ssh.c \
            ../$(PUTTY)/ssh/userauth2-client.c \
            ../$(PUTTY)/windows/agent-client.c \
            ../$(PUTTY)/windows/gss.c \
            ../$(PUTTY)/windows/sharing.c \
            ../$(PUTTY)/callback.c \
            ../$(PUTTY)/timing.c \
            ../$(PUTTY)/windows/handle-wait.c \
            ../$(PUTTY)/windows/select-gui.c \
            ../$(PUTTY)/terminal/bidi.c \
            ../$(PUTTY)/terminal/lineedit.c \
            ../$(PUTTY)/ldisc.c \
            ../$(PUTTY)/config.c \
            ../$(PUTTY)/dialog.c \
            ../$(PUTTY)/windows/controls.c \
            ../$(PUTTY)/windows/config.c \
            ../$(PUTTY)/windows/printing.c \
            ../$(PUTTY)/windows/jump-list.c \
            ../$(PUTTY)/windows/sizetip.c \
            ../$(PUTTY)/windows/help.c \
            ../$(PUTTY)/ssh/bpp1.c \
            ../$(PUTTY)/ssh/bpp2.c \
            ../$(PUTTY)/ssh/bpp-bare.c \
            ../$(PUTTY)/ssh/ca-config.c \
            ../$(PUTTY)/ssh/censor1.c \
            ../$(PUTTY)/ssh/censor2.c \
            ../$(PUTTY)/ssh/common.c \
            ../$(PUTTY)/ssh/connection1.c \
            ../$(PUTTY)/ssh/connection2.c \
            ../$(PUTTY)/ssh/crc-attack-detector.c \
            ../$(PUTTY)/ssh/gssc.c \
            ../$(PUTTY)/ssh/login1.c \
            ../$(PUTTY)/ssh/nocompress.c \
            ../$(PUTTY)/ssh/pgssapi.c \
            ../$(PUTTY)/ssh/portfwd.c \
            ../$(PUTTY)/sshpubk.c \
            ../$(PUTTY)/sshrand.c \
            ../$(PUTTY)/ssh/transient-hostkey-cache.c \
            ../$(PUTTY)/ssh/transport2.c \
            ../$(PUTTY)/ssh/verstring.c \
            ../$(PUTTY)/ssh/x11fwd.c \
            ../$(PUTTY)/ssh/zlib.c \
            ../$(PUTTY)/windows/noise.c \
            ../$(PUTTY)/windows/handle-io.c \
            ../$(PUTTY)/pinger.c \
            ../$(PUTTY)/stubs/no-console.c \
            ../$(PUTTY)/stubs/null-lp.c \
            ../$(PUTTY)/stubs/null-cipher.c \
            ../$(PUTTY)/stubs/null-key.c \
            ../$(PUTTY)/stubs/null-mac.c \
            ../$(PUTTY)/stubs/null-opener.c \
            ../$(PUTTY)/stubs/null-plug.c \
            ../$(PUTTY)/stubs/null-seat.c \
            ../$(PUTTY)/stubs/null-socket.c \
            $(OBJDIR)/commitid.c\
            ../be_list.c \
            ../windows/dialog.c \
            ../windows/pastedlg.c \
            ../windows/pointerarray.c \
            ../windows/putty.c \
            ../windows/shinydialogbox.c \
            ../windows/tabbar.c \
            ../windows/window.c \
            ../windows/conpty.c \
            ../windows/unicode_public.c \
            ../windows/sftp/sftpbe.c \
            ../windows/sftp/sftpfxp.c \
            ../windows/sftp/sftpcli.c \
            ../windows/sftp/sftpwcm.c \
            ../windows/sftp/sftpcmd.c \
            ../windows/sftp/sftpinit.c \
            ../windows/sftp/sftpcmdcd.c \
            ../windows/sftp/sftpcmdmkdir.c \
            ../windows/sftp/sftpcmdls.c \
            ../windows/sftp/sftpcmdrm.c \
            ../windows/sftp/sftpcmdget.c \
            ../windows/sftp/sftpcmdput.c \
            ../windows/sftp/sftpcmdchmod.c \
            ../windows/sftp/sftpcmdmv.c \
            ../windows/sftp/sftpgetput.c \
            ../windows/sftp/sftpprogressbar.c \
            ../windows/sftp/sftpcompletion.c \
            ../windows/sftp/sftpcompletion_readdir.c \
            ../windows/sftp/sftpargs.c \
            ../windows/sftp/sftputil.c \
            ../windows/sftp/sftpunicode.c \
            ../windows/sftp/linenoise/linenoise.c \
            ../windows/sftp/psftp.c \
            ../$(PUTTY)/ssh/sftpcommon.c \
            ../$(PUTTY)/psftpcommon.c \
            ../windows/anchor.c \
            ../windows/finddlg.c \
            ../windows/find/find.c \
            ../windows/find/finditerator.c \
            ../windows/find/kmp.c \
            ../windows/find/ucase.c \
            ../windows/find/uchar.c \
            ../windows/terminal_public.c

RESOURCE := ../windows/putty.rc

getobjdir = $(patsubst %,$(OBJDIR)/%.$(2),$(subst /,__,$(subst $(PUTTY)/,,$(subst ../,,$(basename $(1))))))

$(call getobjdir,../$(PUTTY)/crypto/aes-ni.c,o): CFLAGS += -msse4.1 -maes
$(call getobjdir,../$(PUTTY)/crypto/sha256-ni.c ../$(PUTTY)/crypto/sha1-ni.c,o): CFLAGS += -msse4.1 -msha
$(call getobjdir,../$(PUTTY)/crypto/aesgcm-clmul.c,o): CFLAGS += -msse4.1 -mpclmul

$(OBJDIR)/licence.h: ../$(PUTTY)/LICENCE | $(OBJDIR)
	cmake -DLICENCE_FILE=$< -DOUTPUT_FILE=$@ -P ../$(PUTTY)/cmake/licence.cmake

$(call getobjdir,../windows/dialog.c,o): $(OBJDIR)/licence.h

.PHONY: $(OBJDIR)/commitid.c.tmp
$(OBJDIR)/commitid.c.tmp: | $(OBJDIR)
	@cd ..; cmake -DGIT_EXECUTABLE=git -DOUTPUT_FILE=windows/$@ -DOUTPUT_TYPE=header -P $(PUTTY)/cmake/gitcommit.cmake

$(OBJDIR)/commitid.c: $(OBJDIR)/commitid.c.tmp
	@cmp -s $< $@ || cp $< $@

$(call getobjdir,$(OBJDIR)/commitid.c,o): $(OBJDIR)/commitid.c

$(OBJDIR):
	mkdir -p $(OBJDIR)

OBJECTS := $(call getobjdir,$(SOURCES),o)
DFILES := $(call getobjdir,$(SOURCES),d)

-include $(DFILES)

$(foreach SOURCE,$(SOURCES),$(eval $(call getobjdir,$(SOURCE),o): SOURCE := $(SOURCE)))
$(OBJECTS): | $(OBJDIR)
	$(CC) $(COMPAT) $(CFLAGS) $(XFLAGS) -MMD -MF $(@:.o=.d) -c $(SOURCE) -o $@

-include $(OBJDIR)/putty.res.d

$(OBJDIR)/putty.res.o: $(RESOURCE) $(OBJDIR)/licence.h $(wildcard ../windows/icons/*) | $(OBJDIR)
	$(RC) $(RCFL) $(RCFLAGS) --preprocessor-arg -MMD --preprocessor-arg -MF$(@:.o=.d) --preprocessor-arg -MT$@ --preprocessor-arg -DRC_INVOKED --preprocessor-arg -xc-header $(RESOURCE) -o $@

putty++.exe: $(OBJECTS) $(OBJDIR)/putty.res.o
	$(CC) -mwindows $(LDFLAGS) -o $@ -Wl,-Map,$(OBJDIR)/putty.map $^ -ladvapi32 -lcomdlg32 -lgdi32 -limm32 -lole32 -lshell32 -luser32 -lcomctl32 -lkernel32 -lshlwapi

clean:
	rm -rf $(OBJDIR) *.exe

FORCE:
