
#define IDI_BACKEND_RAW       501
#define IDI_BACKEND_TELNET    502
#define IDI_BACKEND_RLOGIN    503
#define IDI_BACKEND_SSH       504
#define IDI_BACKEND_SSHCONN   505
#define IDI_BACKEND_SERIAL    506
#define IDI_BACKEND_SUPDUP    507
#define IDI_BACKEND_FIRST     IDI_BACKEND_RAW
#define IDI_BACKEND_LAST      IDI_BACKEND_SUPDUP

#define IDR_CLOSETAB          1530
#define IDR_CLOSETAB_INACT    1531
#define IDR_CLOSETAB_HOVER    1532
#define IDR_CLOSETAB_PUSH     1533
